---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0caf07637eda19d9c
      InstanceType: t2.micro
      SecurityGroups: 
      - Ref: SSHSecurityGroup
      KeyName: EC2 Tutorial
  
  DataBase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups:
      - Ref: SSHSecurityGroup
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: root
      MasterUserPassword: admin
      DeletionPolicy: Snapshot

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: stack_EC2_RDS
      GroupDescription: Enable SSH and DB access
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
  
